//
//  ResourceStrings.h
//  EMBRACE
//
//  Created by James Rodriguez on 7/21/16.
//  Copyright © 2016 Andreea Danielescu. All rights reserved.
//

#ifndef ResourceStrings_h
#define ALL_CHAPTERS @"All_Chapters"
#define ANIMATE @"animate"
#define ANYWHERE @"anywhere"
#define APPEAR @"appear"
#define APPEARAUTOWITHDELAY @"appearAutoWithDelay"
#define APPEAR_OBJECT @"Appear Object"
#define AREA @"area"
#define CHANGEZINDEX @"changeZIndex"
#define CHECK @"check"
#define CHECKANDSWAP @"checkAndSwap"
#define CHECKDOWN @"checkDown"
#define CHECKLEFT @"checkLeft"
#define CHECKPATH @"checkPath"
#define CHECKRIGHT @"checkRight"
#define CHECKUP @"checkUp"
#define DASH_INTRO @"-Intro"
#define DASH_PM @"-PM"
#define DEF_E @"_def_E"
#define DEF_S @"_def_S"
#define DISAPPEAR_TXT @"disappear"
#define DISAPPEARAUTO @"disappearAuto"
#define DISAPPEARAUTOWITHDELAY @"disappearAutoWithDelay"
#define DISAPPEAR_OBJECT @"Disappear Object"
#define E @"E"
#define EMPTYSTRING @""
#define ENGLISH_TXT @"English"
#define ERROR_NOISE @"Error Noise"
#define MORE_ERROR @"More to do sound"

#define ERROR_FEEDBACK_NOISE @"Error Feedback Noise"
#define GROUP_TXT @"group"
#define GROUPAUTO @"groupAuto"
#define GROUP_OBJECTS @"Group Objects"
#define HOTSPOT @"hotspot"
#define IM_INSTRUCTIONS @"Which did you imagine?"
#define INTERACTIONTYPE @"interactionType"
#define INTERVENTION @"Intervention"
#define INTRO @"Intro"
#define LIBRARY @"Library"
#define LOCATION @"Location"
#define MANIPULATIONOBJECT @"manipulationObject"
#define MOVE @"move"
#define MOVE_OBJECT @"Move Object"
#define MOVETOLOCATION @"moveToLocation"
#define NULL_TXT @"NULL"
#define OBJECT @"object"
#define OBJECTS @"objects"
#define PAGE_STATISTICS @"Page Statistics"
#define PAUSE @"pause"
#define PLAY_ERROR_NOISE @"Play Error Noise"
#define PLAY_SOUND @"Play Sound"
#define PLAY_WORD @"Play Word"
#define PLAY_WORD_WITH_DEF @"Play Word with Definition"
#define PLAYSOUND @"playSound"
#define PM1 @"PM-1"
#define PM2 @"PM-2"
#define PM3 @"PM-3"
#define PM4 @"PM-4"
#define PM5 @"PM-5"
#define PM_CUSTOM @"PM_CUSTOM"
#define POSTSENTENCE_SCRIPT_AUDIO @"Post-Sentence Script Audio"
#define PRESENTENCE_SCRIPT_AUDIO @"Pre-Sentence Script Audio"
#define ResourceStrings_h
#define RETURN_TO_LIBRARY @"Return to Library"
#define S @"S"
#define SELECT_MENU_ITEM @"Select Menu Item"
#define SENTENCE_AUDIO @"Sentence Audio"
#define SHAKEORTAP @"shakeOrTap"
#define SPANISH_TXT @"Spanish"
#define STOP @"stop"
#define SUBJECT @"subject"
#define SWAPIMAGE @"swapImage"
#define TAP_OBJECT @"Tap Object"
#define TAPTOANIMATE @"tapToAnimate"
#define TAPWORD @"tapWord"
#define TRANSFERANDDISAPPEAR_TXT @"transferAndDisappear"
#define TRANSFERANDGROUP_TXT @"transferAndGroup"
#define UNGROUP_AND_STAY_OBJECTS @"Ungroup and Stay Objects"
#define UNGROUP_OBJECTS @"Ungroup Objects"
#define UNGROUP_TXT @"ungroup"
#define UNGROUPANDSTAY @"ungroupAndStay"
#define WAYPOINT @"Waypoint"

#endif /* ResourceStrings_h */
